#TargetName : Dependencies
#<TAB>commands
PROJ_NAME=DISTANCE_MEASUREMENT_USING_ATMEGA32_AND_HCSRO4

SRC=src/main.c src/timer.c src/ultrasonic.c 


#To check if the OS is Windows or Linux and set the executable file extension and delete command accordingly.
ifdef OS
	RM = del /q
	FixPath = $(subst /,\,$1)
	EXEC = exe
else
	ifeq ($(shell uname), Linux)
		RM = rm -rf
		FixPath = $1
	  EXEC = out
	endif
endif

Build : $(SRC)
	gcc $(SRC) -Iinc -Iunity -o $(call FixPath,$(PROJ_NAME).$(EXEC)) -lm

Run : Build
	./$(call FixPath,$(PROJ_NAME).$(hex))

static_analysis:
	cppcheck --enable=all $(SRC)

dynamic_analysis: Build
	valgrind ./$(call FixPath,$(PROJ_NAME).$(hex))

coverage:
	gcc -fprofile-arcs -ftest-coverage $(SRC) -Iinc -o $(call FixPath,$(PROJ_NAME).$(hex)) -lm
	./$(call FixPath,$(PROJ_NAME).$(EXEC))
	gcov -a src/main.c src/timer.c src/ultrasonic.c

Clean:
	$(RM) $(call FixPath,*.out)